### ISSUE TITLE
allow create-session[*] to have specified host and port separatedly instead of URI

### ISSUE THREAD

**Issue by m-g-r** [daveliepmann/uruk#12]
Hello,

We usually store the connections as plists now, so it would be nice to have an interface to the an interface to the other ContentSource methods specified in
https://docs.marklogic.com/javadoc/xcc/com/marklogic/xcc/ContentSourceFactory.html
that base on host and port instead of uri.

And in addition to this specifying SecurityOptions could also get relevant.

What do you think about it? Right now I have some glue code that joins host and port to an xcc://-uri, but I'd like to get rid of that code.

Thank you and cheers,
Max

**Comment by daveliepmann** [comment]
If I understand you correctly, Uruk might already support this, and just not be documented well enough.

Passing the result of [`make-hosted-content-source`](https://github.com/daveliepmann/uruk/blob/master/src/uruk/core.clj#L532) to `create-session` may address your use case. It accepts the result of [`make-security-options`](https://github.com/daveliepmann/uruk/blob/master/src/uruk/core.clj#L481) as well.

There are some [tests](https://github.com/daveliepmann/uruk/blob/master/test/uruk/core_test.clj#L255) that could serve as example uses of those functions, but I'll carve out some time this week to write up something more clear. Apologies for the omission. If possible I'd like to hear more about how it goes using these alternatives—of if they don't address your use case—since the vast majority of my usage is with a plain database map.

**Comment by m-g-r** [comment]
Hi Dave,

thanks for the quick reply!

> If I understand you correctly, Uruk might already support this

Perfect! Yes, that is just what I wanted. I just haven't seen it.

Actually, it seems that `create-session*` should use

```
(make-uri-content-source uri)
```

instead of calling 

```
(ContentSourceFactory/newContentSource (URI. uri))
```

right? That way you are led in the direction of `make-*-content-source` when reading the source as well.

From looking at the code I get the feeling that some functionally seems to be implemented in double in `create-session`, `create-session*` and `make-*-content-source`, as `create-session*` might optionally be also called with a content-source (and then perhaps modify it).

Otherwise, I suggest that there might be a version of `create-session` that has an argument list with content-source but without config-options, so just `[db content-source]` as there is also a variant that has just `[db-info]` and not `[db-info {... :config-options}]`.

Right now I would call it like this with two empty maps which is a bit strange:

```
(uruk/create-session {} (uruk/make-hosted-content-source host port {:user ...}) {})
```

Thanks a lot,
Max

**Comment by daveliepmann** [comment]
I sketched out a potential solution in the `dev` branch. 

If you need to create a content source independently from creating a session, then at session creation time you can either specify database options with `create-session` or use the default content source options with `create-default-session` (which takes an optional config map). I believe this will cover all the various parameter permutations without the need for empty maps as placeholders.

Please let me know your thoughts. If all is OK then I can document, test, and release.

**Comment by m-g-r** [comment]
So, with that code my call would be:

```
(uruk/create-default-session (uruk/make-hosted-content-source host port {:user ...}))
```

right? That would  be a bit shorter. But you have a better overview, what would constitute a good interface.

Thanks! Max

**Comment by daveliepmann** [comment]
Roger. Adding documentation and tests now. Hope to release soon.

**Comment by daveliepmann** [comment]
OK, Uruk version 0.3.3 should take care of this. Please re-open if something is amiss.

**Comment by m-g-r** [comment]
Works like a charm. Thanks!

**Comment by m-g-r** [comment]
tiny simplification, as make-uri-content-source calls URI. already

[core.clj-URI.patch.txt](https://github.com/daveliepmann/uruk/files/493394/core.clj-URI.patch.txt)

**Comment by daveliepmann** [comment]
Thanks
